config:

  grafana:

    # URL of the target grafana-server.
    url: localhost:3000

    # User account name with admin rights on target grafana-server.
    user: admin

    # Password of account with admin rights on target grafana-server.
    password: admin

  ldap:

    # Set to True if NTLM should be used for LDAP.
    useNTLM: True

    # If True, SSL will be used for connection to LDAP.
    useSSL: False

    # URL of the source LDAP-Server.
    url: ldap.forumsys.com

    port: 389

    # Group search-base of the source LDAP-Server.
    groupSearchBase: dc=example,dc=com

    # Filter that should be used for the group search.
    groupSearchFilter:

    userSearchBase: dc=example,dc=com

    userSearchFilter:

    # Attribute name under which the members of a group object can be found.
    memberAttributeName: uniqueMember

    # Name of the attribute which should be used as login in grafana.
    userLoginAttribute: uid

    # Name of the attribute which should be used as Name in grafana.
    userNameAttribute: cn

    # Name of the attribute which should be used as mail in grafana.
    userMailAttribute: mail

    # Login for the LDAP-Server.
    login: test\cn=read-only-admin,dc=example,dc=com

    # Password for the LDAP-Server.
    password: password

  tryRun: False
